FROM docker.io/library/ubuntu:20.04 as build

RUN export DEBIAN_FRONTEND=noninteractive && \
    ln -fs /usr/share/zoneinfo/UTC /etc/localtime

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y build-essential apt-utils curl automake g++ \
    llvm clang zlib1g-dev libc6 libelf-dev libdw-dev cmake git golang && \
    apt-get purge --auto-remove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY get_linux.sh ./
RUN chmod +x get_linux.sh && ./get_linux.sh
RUN cd /src/linux/tools/bpf/bpftool && make

#COPY get_pahole.sh ./
#RUN chmod +x get_pahole.sh && ./get_pahole.sh

ARG CACHEBUST=1
RUN mkdir -p go2/src/github.com/noironetworks && \
    cd  go2/src/github.com/noironetworks && \
    git clone https://github.com/noironetworks/kubpf.git && \
    cd kubpf && make && cd ebpf/kernel && make

FROM scratch as artifacts
COPY --from=build /src/linux/tools/bpf/bpftool/bpftool /out/
COPY --from=build /go2/src/github.com/noironetworks/kubpf/ebpf/kernel/bpf_cgroup_kern.o /out/
COPY --from=build /go2/src/github.com/noironetworks/kubpf/statsagent /out/

