apiVersion: v1
kind: Namespace
metadata:
  name: statsagent-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: statsagent
  namespace: statsagent-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: statsagent-role
rules:
- apiGroups: [""]
  resources: ["pods","services", "endpoints", "namespaces"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: statsagent-role-binding
subjects:
- kind: ServiceAccount
  name: statsagent
  namespace: statsagent-system
roleRef:
  kind: ClusterRole
  name: statsagent-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: statsagent
  namespace: statsagent-system
  labels:
    k8s-app: statsagent
spec:
  selector:
    matchLabels:
      name: statsagent
  template:
    metadata:
      labels:
        name: statsagent
      annotations:
        prometheus.io/scrape_port: "8010"
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: statsagent
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: statsagent
        image: stalactite/statsagent:latest
        env:
          - name: KUBERNETES_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CGROUP_ROOT
            # Change this suitably for the environment
            value: "/sys/fs/cgroup/unified/kubepods.slice"
        volumeMounts:
        - mountPath: /ebpf
          name: ebpf-host-mount
        - mountPath: /cgroup
          name: cgroupv2-host-mount
        - mountPath: /lib/modules
          name: hostmodules
          readOnly: true
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
            - NET_ADMIN
            - SYS_MODULE
          privileged: true
      hostNetwork: true
      volumes:
      - name: ebpf-host-mount
        hostPath:
          path: /sys/fs/bpf
      - name: cgroupv2-host-mount
        hostPath:
          path: /sys/fs/cgroup
      - name: hostmodules
        hostPath:
          path: /lib/modules
